"""Per-launch token (PROJECT_BRIEF.md §9.1).

The backend is an HTTP server on loopback that holds the user's provider keys.
Without auth, any page the user happens to have open could `fetch()` it and
spend their money — WebSockets do not even get a CORS preflight to stop them.

The token is generated by the parent process (scripts/dev.mjs in dev, Tauri when
packaged) and handed over on stdin. Never argv — argv is world-readable in the
process list. Never an environment variable — those leak into child processes
and crash dumps.
"""

from __future__ import annotations

import hmac
import sys

_TOKEN: str | None = None

#: REST sends the token in this header.
HEADER_NAME = "X-Agent-Studio-Token"

#: Browsers cannot set headers on a WebSocket handshake, so the token rides in
#: the subprotocol list instead of the query string — query strings end up in
#: access logs and browser history, subprotocols do not.
WS_PROTOCOL = "agent-studio.v1"
WS_TOKEN_PREFIX = "token."


class TokenNotConfigured(RuntimeError):
    pass


def set_token(token: str) -> None:
    global _TOKEN
    token = token.strip()
    if not token:
        raise ValueError("refusing to arm an empty session token")
    _TOKEN = token


def read_token_from_stdin() -> str:
    """Consume the first line of stdin as the session token."""
    line = sys.stdin.readline()
    if not line:
        raise TokenNotConfigured(
            "no session token on stdin. The backend is started by its parent "
            "(scripts/dev.mjs in dev, Tauri when packaged), which writes the "
            "token as the first line of stdin."
        )
    return line.strip()


def is_valid(candidate: str | None) -> bool:
    """Constant-time comparison; False until a token has been armed."""
    if _TOKEN is None or not candidate:
        return False
    return hmac.compare_digest(_TOKEN, candidate)


def token_from_ws_protocols(protocols: list[str] | None) -> str | None:
    """Pull `token.<value>` out of the offered WebSocket subprotocols."""
    for proto in protocols or []:
        proto = proto.strip()
        if proto.startswith(WS_TOKEN_PREFIX):
            return proto[len(WS_TOKEN_PREFIX) :]
    return None


def _reset_for_tests() -> None:
    global _TOKEN
    _TOKEN = None
